version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
